version: '2'
services:
    smaback-app:
        image: smaback
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://smaback-postgresql:5432/smaBack
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    smaback-postgresql:
        extends:
            file: postgresql.yml
            service: smaback-postgresql
